name: Push LTX-Video Model to Replicate
on:
  workflow_dispatch:
    inputs:
      model_name:
        default: 'dyotis/ltx-video-custom'
        description: 'latest LTX video version 9.7'
        required: true      
jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Free disk pace
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_CLI_AUTH_TOKEN }}

      - name: Push to Replicate
        run: cog push r8.im/${{ inputs.model_name }}
